# Generated by Django 5.2.1 on 2025-09-20 19:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='admin',
            new_name='created_by',
        ),
        migrations.RemoveField(
            model_name='project',
            name='gitrepo',
        ),
        migrations.RemoveField(
            model_name='project',
            name='title',
        ),
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default='New Project', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='repo_url',
            field=models.URLField(default='https://github.com/example/repo', max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='contributed_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
