# Generated by Django 5.2.1 on 2025-12-24 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0004_alter_project_contributors'),
        ('task', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCommit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_id', models.CharField(max_length=40)),
                ('message', models.TextField()),
                ('step', models.CharField(blank=True, help_text='Optional step name like clone/build/test/push', max_length=100)),
                ('is_successful', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_commits', to=settings.AUTH_USER_MODEL)),
                ('github_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='task.task')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_commits', to='project.project')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
